# Global
namespace: haystack-rag
hostname: rag.local

secret:
  opensearchPassword: ChangeMe123!
  openaiApiKey: ""

frontend:
  replicaCount: 1
  port: 80
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  env:
    REACT_APP_HAYSTACK_API_URL: /api
    LOG_LEVEL: info
  livenessProbe:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

query:
  replicaCount: 1
  port: 8002
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    LOG_LEVEL: info
  livenessProbe:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

indexing:
  replicaCount: 1
  port: 8001
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    LOG_LEVEL: info
  livenessProbe:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

opensearch:
  replicaCount: 1
  port: 9200
  service:
    type: ClusterIP
  storageClass: local-path
  storageSize: 10Gi
  javaOpts: "-Xms512m -Xmx512m"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

image:
  registry: public.ecr.aws/e8b9x6t1
  tag: 0.1.0

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: haystack-rag-strip-api@kubernetescrd,haystack-rag-buffering@kubernetescrd
  buffering:
    enabled: true
    maxRequestBodyBytes: 104857600
    memRequestBodyBytes: 10485760
  timeouts:
    readTimeout: 600
    writeTimeout: 600
    idleTimeout: 600
