# Global
namespace: haystack-rag
hostname: rag.local

secret:
  opensearchPassword: ChangeMe123!
  openaiApiKey: ""

frontend:
  replicaCount: 1
  port: 80
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  env:
    REACT_APP_HAYSTACK_API_URL: /api
    LOG_LEVEL: info
  livenessProbe:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

query:
  replicaCount: 1
  port: 8002
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
      ephemeral-storage: "2Gi"
    limits:
      memory: "2Gi"
      cpu: "500m"
      ephemeral-storage: "20Gi"
  env:
    LOG_LEVEL: info
  livenessProbe:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

indexing:
  replicaCount: 1
  port: 8001
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
      ephemeral-storage: "2Gi"
    limits:
      memory: "2Gi"
      cpu: "500m"
      ephemeral-storage: "20Gi"
  env:
    LOG_LEVEL: info
  livenessProbe:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

opensearch:
  replicaCount: 1
  port: 9200
  service:
    type: ClusterIP
  storageClass: local-path
  storageSize: 10Gi
  javaOpts: "-Xms512m -Xmx512m"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "4Gi"
      cpu: "1000m"
      ephemeral-storage: "4Gi"

image:
  registry: public.ecr.aws/e8b9x6t1
  tag: 0.1.0

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: haystack-rag-strip-api@kubernetescrd,haystack-rag-buffering@kubernetescrd
  buffering:
    enabled: true
    maxRequestBodyBytes: 104857600
    memRequestBodyBytes: 10485760
  timeouts:
    readTimeout: 600
    writeTimeout: 600
    idleTimeout: 600
