# templates/deployment-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-frontend
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
      - name: app
        image: {{ .Values.image.registry }}/haystack-frontend:{{ .Values.image.tag }}
        args: ["nginx", "-g", "daemon off;"]
        env:
        {{- range $key, $value := .Values.frontend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.livenessProbe.path }}
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.readinessProbe.path }}
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}