apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rag
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: buffering
spec:
  entryPoints: [web]
  routes:
  - match: Host(`{{ .Values.hostname }}`) && ( PathPrefix(`/api/files`) || PathPrefix(`/api/upload`) )
    kind: Rule
    services:
    - name: rag-indexing
      port: 8001
      serversTransport: timeouts
    middlewares:
    - name: strip-api
  - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: rag-query
      port: 8002
      serversTransport: timeouts
    middlewares:
    - name: strip-api
  - match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: rag-frontend
      port: 80
      serversTransport: timeouts
