apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: buffering
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.ingress.buffering.maxRequestBodyBytes }}
    memRequestBodyBytes: {{ .Values.ingress.buffering.memRequestBodyBytes }}
