apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api
