apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.opensearch.storageClass }}
  resources:
    requests:
      storage: {{ .Values.opensearch.storageSize }}
