apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
stringData:
  OPENSEARCH_PASSWORD: {{ .Values.secret.opensearchPassword | quote }}
  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | quote }}
