# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Values.namespace }}
  labels:
    app: opensearch
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  clusterIP: None            # headless; drop this line for normal ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: rag-indexing
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-indexing
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  selector:
    app: rag-indexing
  ports:
    - port: 8001
      targetPort: 8001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rag-query
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-query
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  selector:
    app: rag-query
  ports:
    - port: 8002
      targetPort: 8002
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-frontend
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  selector:
    app: rag-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
