# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Values.namespace }}
  labels:
    app: opensearch
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opensearch.service.type }}
  clusterIP: None            # headless; drop this line for normal ClusterIP
  ports:
    - name: http
      port: {{ .Values.opensearch.port }}
      targetPort: {{ .Values.opensearch.port }}
  selector:
    app: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: rag-indexing
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-indexing
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.indexing.service.type }}
  selector:
    app: rag-indexing
  ports:
    - port: {{ .Values.indexing.port }}
      targetPort: {{ .Values.indexing.port }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rag-query
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-query
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.query.service.type }}
  selector:
    app: rag-query
  ports:
    - port: {{ .Values.query.port }}
      targetPort: {{ .Values.query.port }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-frontend
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: rag-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      name: http
