apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: timeouts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  forwardingTimeouts:
    dialTimeout: {{ .Values.ingress.timeouts.readTimeout }}s
    responseHeaderTimeout: {{ .Values.ingress.timeouts.writeTimeout }}s
    idleConnTimeout: {{ .Values.ingress.timeouts.idleTimeout }}s
