name: Helm chart lint & schema check

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CHART_DIR: "."          # Chart is at repo root

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # 1  Checkout repo
      - uses: actions/checkout@v4

      # 2  Install Helm
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.3

      # 3  Install kubeconform v0.6.5
      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/download/v0.6.5/kubeconform-linux-amd64.tar.gz \
            | sudo tar -xz -C /usr/local/bin kubeconform
          kubeconform -v

      # 4  Download Traefik CRD schema once
      - name: Fetch Traefik CRD schema
        run: |
          mkdir -p /tmp/schemas
          curl -sSL \
            https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-v1alpha1.yml \
            -o /tmp/schemas/traefik-crd.yaml

      # 5  Strict Helm lint
      - name: Helm strict lint
        run: |
          helm lint --strict "$CHART_DIR" -f "$CHART_DIR/values.yaml"

      # 6  Render & schema‑validate (core + Traefik CRDs)
      - name: Render & kubeconform
        run: |
          helm template "$CHART_DIR" | \
            kubeconform -strict -summary \
              -schema-location default \
              -schema-location file:///tmp/schemas/traefik-crd.yaml
